FROM oraclelinux:9

LABEL maintainer="heinloth@cs.fau.de"

ENV LC_ALL C.UTF-8

LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="lp-build/oraclelinux-9"
LABEL org.label-schema.vendor="Friedrich-Alexander-Universität Erlangen-Nürnberg / Lehrstuhl für Informatik 4"

RUN yum install -y nano less file make diffutils gcc gcc-c++ clang
